logging:
  level: info

tasks:
- id: increase_volume
  name: Increase Volume
  cmd: wpctl
  args:
  - set-volume
  - '@DEFAULT_AUDIO_SINK@'
  - 5%+
- id: decrease_volume
  name: Decrease Volume
  cmd: wpctl
  args:
  - set-volume
  - '@DEFAULT_AUDIO_SINK@'
  - 5%-
- id: decrease_volume_script
  name: Decrease Volume Script
  script: |
    #!/bin/bash
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
